In [1]:
import pandas as pd
import numpy as np

In [3]:
data = {
    'name': ['alice','bob',None,'david','alice'],
    'age': ['25','thirty','35',None,'25'],
    'salary': [50000,60000,None,55000,50000],
    'join_date': ['2025-01-01','not available','2025-05-01','2025-11-01','2025-01-01']
    }
df = pd.DataFrame(data)
df

    name     age   salary      join_date
0  alice      25  50000.0     2025-01-01
1    bob  thirty  60000.0  not available
2    NaN      35      NaN     2025-05-01
3  david     NaN  55000.0     2025-11-01
4  alice      25  50000.0     2025-01-01

In [5]:
df.info()
df.describe(include='all')

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       4 non-null      str
 1   age        4 non-null      str
 2   salary     4 non-null      float64
 3   join_date  5 non-null      str
dtypes: float64(1), str(3)
memory usage: 292.0 bytes

         name  age        salary   join_date
count       4    4      4.000000           5
unique      3    3           NaN           4
top     alice   25           NaN  2025-01-01
freq        2    2           NaN           2
mean      NaN  NaN  53750.000000         NaN
std       NaN  NaN   4787.135539         NaN
min       NaN  NaN  50000.000000         NaN
25%       NaN  NaN  50000.000000         NaN
50%       NaN  NaN  52500.000000         NaN
75%       NaN  NaN  56250.000000         NaN
max       NaN  NaN  60000.000000         NaN

In [7]:
df.isnull().sum()

name         1
age          1
salary       1
join_date    0
dtype: int64

In [8]:
df['age'] = df['age'].replace('thirty', np.nan)
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['age'] = df['age'].fillna(df['age'].mean())

df['name'] = df['name'].fillna('unknown')
df['salary'] = df['salary'].ffill()

In [9]:
df['join_date'] = pd.to_datetime(df['join_date'], errors='coerce')

In [10]:
df =df.drop_duplicates()

In [14]:
print(df)
print(df.dtypes)

      name        age   salary  join_date
0    alice  25.000000  50000.0 2025-01-01
1      bob  28.333333  60000.0        NaT
2  unknown  35.000000  60000.0 2025-05-01
3    david  28.333333  55000.0 2025-11-01
name                    str
age                 float64
salary              float64
join_date    datetime64[us]
dtype: object

In [15]:
df.rename(columns={'name': 'first_name','salary': 'saalry($)'})

  first_name        age  saalry($)  join_date
0      alice  25.000000    50000.0 2025-01-01
1        bob  28.333333    60000.0        NaT
2    unknown  35.000000    60000.0 2025-05-01
3      david  28.333333    55000.0 2025-11-01