In [1]:
import pandas as pd
import numpy as np

data = {
    'name': ['alice','bob','charles','david','eva','alice'],
    'age': ['25','np.nan','30','29','NaN','25'],
    'gender': ['female','male','male','np.nan','female','female'],
    'country': ['USA','usa','canda','CANADA','UK','USA'],
    'quantity': [2, 1, 3, 5, 2, 2],
    'unit_price': [20,15,np.nan,10,30,20] 
}

df = pd.DataFrame(data)
df

      name     age  gender country  quantity  unit_price
0    alice      25  female     USA         2        20.0
1      bob  np.nan    male     usa         1        15.0
2  charles      30    male   canda         3         NaN
3    david      29  np.nan  CANADA         5        10.0
4      eva     NaN  female      UK         2        30.0
5    alice      25  female     USA         2        20.0

In [5]:
df.fillna(0)

      name     age  gender country  quantity  unit_price
0    alice      25  female     USA         2        20.0
1      bob  np.nan    male     usa         1        15.0
2  charles      30    male   canda         3         0.0
3    david      29  np.nan  CANADA         5        10.0
4      eva     NaN  female      UK         2        30.0
5    alice      25  female     USA         2        20.0

In [7]:
df.dropna()

    name     age  gender country  quantity  unit_price
0  alice      25  female     USA         2        20.0
1    bob  np.nan    male     usa         1        15.0
3  david      29  np.nan  CANADA         5        10.0
4    eva     NaN  female      UK         2        30.0
5  alice      25  female     USA         2        20.0

In [9]:
df.drop_duplicates()

      name     age  gender country  quantity  unit_price
0    alice      25  female     USA         2        20.0
1      bob  np.nan    male     usa         1        15.0
2  charles      30    male   canda         3         NaN
3    david      29  np.nan  CANADA         5        10.0
4      eva     NaN  female      UK         2        30.0

In [13]:
df['country'] = df['country'].str.lower()
print(df)

      name     age  gender country  quantity  unit_price
0    alice      25  female     usa         2        20.0
1      bob  np.nan    male     usa         1        15.0
2  charles      30    male   canda         3         NaN
3    david      29  np.nan  canada         5        10.0
4      eva     NaN  female      uk         2        30.0
5    alice      25  female     usa         2        20.0

In [19]:
df['age'] = pd.to_numeric(df['age'],errors = 'coerce')

df['age'] = df['age'].fillna(df['age'].median())
df['age']= df['age'].astype(int)

print(df)

      name  age  gender country  quantity  unit_price
0    alice   25  female     usa         2        20.0
1      bob   27    male     usa         1        15.0
2  charles   30    male   canda         3         NaN
3    david   29  np.nan  canada         5        10.0
4      eva   27  female      uk         2        30.0
5    alice   25  female     usa         2        20.0

In [22]:
df['total_price'] = df['quantity'] * df['unit_price']

print('total_price')

total_price

In [6]:
print(df)

      name     age  gender country  quantity  unit_price
0    alice      25  female     USA         2        20.0
1      bob  np.nan    male     usa         1        15.0
2  charles      30    male   canda         3         NaN
3    david      29  np.nan  CANADA         5        10.0
4      eva     NaN  female      UK         2        30.0
5    alice      25  female     USA         2        20.0

In [24]:
pd.get_dummies(df['gender'])

   female   male  np.nan
0    True  False   False
1   False   True   False
2   False   True   False
3   False  False    True
4    True  False   False
5    True  False   False

In [3]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\hp\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\hp\anaconda3\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.8.0 in c:\users\hp\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\hp\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hp\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [12]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
df[['income']] = scaler.fit_transform(df[['income']])

KeyError: "None of [Index(['income'], dtype='object')] are in the [columns]"