In [1]:
import pandas as pd

In [12]:
data = {
    'region': ['east','west','east','south','north','north'],
    'name': ['alice','bob','charles','david','eva','darwin'],
    'sales': [200,150,300,100,400,100]
}

df = pd.DataFrame(data)
df

  region     name  sales
0   east    alice    200
1   west      bob    150
2   east  charles    300
3  south    david    100
4  north      eva    400
5  north   darwin    100

In [15]:
grouped = df.groupby('region')

In [16]:
grouped['sales'].sum()

region
east     500
north    500
south    100
west     150
Name: sales, dtype: int64

In [17]:
grouped['sales'].mean()

region
east     250.0
north    250.0
south    100.0
west     150.0
Name: sales, dtype: float64

In [18]:
grouped['sales'].count()

region
east     2
north    2
south    1
west     1
Name: sales, dtype: int64

In [19]:
grouped['sales'].agg(['sum','mean','max','min'])

        sum   mean  max  min
region
east    500  250.0  300  200
north   500  250.0  400  100
south   100  100.0  100  100
west    150  150.0  150  150

In [25]:
df.groupby(['region','sales'])['sales'].sum()

region  sales
east    200      200
        300      300
north   100      100
        400      400
south   100      100
west    150      150
Name: sales, dtype: int64

In [26]:
grouped['sales'].sum().reset_index()

  region  sales
0   east    500
1  north    500
2  south    100
3   west    150

In [32]:
grouped = df.groupby('region')['sales'].sum()
sorted_group = grouped.sort_values(ascending=False)
print(sorted_group)

region
east     500
north    500
west     150
south    100
Name: sales, dtype: int64